<?php

namespace Sabatier\Service;

use Attribute;
use JetBrains\PhpStorm\ExpectedValues;
use Sabatier\Foundation\Networking\HTTPRequestMethod;

/**
 * Represents an action method on a Responder that can be invoked in response to an HTTP request. Actions are always void and can optionally apply decorators to the Response generated by the Responder.
 *
 * This attribute is intended to be applied to public methods of a Responder subclass. It allows the framework to:
 *   1. Determine which method handles a given HTTP request.
 *   2. Optionally, apply a series of ResponseDecorator classes to the Response after the action is executed.
 *
 * Example usage:
 *
 * #[Action(method: HTTPRequestMethod::post, path: "/login", decorators: [JSONDecorator::class, CacheHeaderDecorator::class])]
 * public function login(): void {
 *     // mutate internal state or perform side effects
 * }
 */
#[Attribute(Attribute::TARGET_METHOD)]
final readonly class Action
{
    /**
     * @param string $method The HTTP method this action handles. Expected values: POST, PUT, PATCH, DELETE.
     * @param string|null $path Optional custom path for this action. Defaults to "/<methodName>".
     * @param array<class-string<ResponseDecorator>> $decorators An array of decorator classes to apply to the Response when this action is executed. Each decorator will receive the Response instance and can modify its properties (body, allHeaderFields, statusCode) directly.
     */
    public function __construct(#[ExpectedValues([HTTPRequestMethod::post, HTTPRequestMethod::put, HTTPRequestMethod::patch, HTTPRequestMethod::delete])] public string $method = HTTPRequestMethod::post, public ?string $path = null, public array $decorators = [])
    {
    }
}
