<?php

namespace Sabatier\Service;

/** @var string The domain used for all errors generated by the service. */
const ServiceErrorDomain = "ServiceErrorDomain";
/** @var string The environment variable key used to determine the application's runtime environment. */
const ApplicationEnvironmentKey = "APP_ENV";
/** @var string The value representing a development environment. */
const ApplicationEnvironmentDevelopment = "development";
/** @var string The value representing a production environment. */
const ApplicationEnvironmentProduction = "production";
/** @var string The value representing a testing environment. */
const ApplicationEnvironmentTesting = "testing";
/** @var string The dictionary key used to return the total number of objects in a count request. */
const ServiceResponseCountKey = "count";
/** @var string The URL query item name used to provide a base64-encoded JSON representation of a FetchRequest. */
const ServiceFetchRequestKey = "fetchRequest";
const ServiceObjectIDKey = "objectID";
