<?php

declare(strict_types=1);

namespace Sabatier\Service;

/** @var string The domain used for all errors generated by the service. */
const ServiceErrorDomain = "ServiceErrorDomain";
/** @var string The environment variable key used to determine the application's runtime environment. */
const ApplicationEnvironmentKey = "APP_ENV";
/** @var string The value representing a development environment. */
const ApplicationEnvironmentDevelopment = "development";
/** @var string The value representing a production environment. */
const ApplicationEnvironmentProduction = "production";
/** @var string The value representing a testing environment. */
const ApplicationEnvironmentTesting = "testing";
/** @var string The dictionary key used to return the total number of objects in a count request. */
const ServiceResponseCountKey = "count";
/** @var string The dictionary key used to return the status of a persistent history status-only request. */
const ServiceResponseStatusKey = "status";
/** @var string The URL query item name used to provide a base64-encoded JSON representation of a FetchRequest. */
const ServiceFetchRequestKey = "fetchRequest";
/** @var string The URL query parameter name used to scope persistent history requests to transactions after a given date. */
const PersistentHistoryAfterDateKey = "afterDate";
/** @var string The URL query parameter name used to scope persistent history requests to transactions after a given transaction number. */
const PersistentHistoryAfterTransactionKey = "afterTransaction";
/** @var string The URL query parameter name used to scope persistent history requests to transactions after a given token. */
const PersistentHistoryAfterTokenKey = "afterToken";
/** @var string The URL query parameter name used to specify the result type for a persistent history fetch request. */
const PersistentHistoryResultTypeKey = "resultType";
/** @var string The URL query parameter name used to scope persistent history delete requests to transactions before a given date. */
const PersistentHistoryBeforeDateKey = "beforeDate";
/** @var string The URL query parameter name used to scope persistent history delete requests to transactions before a given transaction number. */
const PersistentHistoryBeforeTransactionKey = "beforeTransaction";
/** @var string The URL query parameter name used to scope persistent history delete requests to transactions before a given token. */
const PersistentHistoryBeforeTokenKey = "beforeToken";
/** @var string The dictionary key used to identify a transaction number within a persistent history transaction. */
const PersistentHistoryTransactionNumberKey = "transactionNumber";
