<?php

declare(strict_types=1);

namespace Sabatier\Service;

/**
 * Defines a strategy for generating a `Response` for a specific `Responder`.
 */
abstract class ResponseStrategy
{
    /** @var Response the `Response` generated by this strategy for the associated `Request`. */
    abstract public Response $response {
        get;
    }

    public function __construct(public readonly Request $request)
    {
    }
}
